- name: Export vManage Policy Lists
  hosts: localhost
  connection: local
  roles:
    - ansible-viptela
  vars:
    file: vmanage-policy.json
  gather_facts: no
  tasks:
    - assert:
        that:
          - vmanage_host is defined and vmanage_host
          - vmanage_user is defined and vmanage_host
          - vmanage_password is defined and vmanage_host
        fail_msg: "vmanage_host, vmanage_user, and vmanage_password must be defined"

    - name: Get policy lists
      vmanage_policy_list_facts:
        user: "{{ vmanage_user }}"
        host: "{{ vmanage_host }}"
        password: "{{ vmanage_password }}"
      register: policy_list_facts

    - name: Get policy definitions
      vmanage_policy_definition_facts:
        user: "{{ vmanage_user }}"
        host: "{{ vmanage_host }}"
        password: "{{ vmanage_password }}"
      register: policy_definition_facts

    - name: Get central policies
      vmanage_central_policy_facts:
        user: "{{ vmanage_user }}"
        host: "{{ vmanage_host }}"
        password: "{{ vmanage_password }}"
      register: central_policy_facts

    - set_fact:
        vmanage_policy:
          policy_lists: "{{ policy_list_facts.policy_lists }}"
          policy_definitions: "{{ policy_definition_facts.policy_definitions }}"
          central_policies: "{{ central_policy_facts.central_policies }}"

    - name: Write out policies to {{ file }}
      copy:
        content: "{{ vmanage_policy | to_nice_json }}"
        dest: "{{ file }}"