- name: Import vManage Policy Lists
  hosts: localhost
  connection: local
  roles:
    - ansible-viptela
  vars:
    file: vmanage-policy.json
  gather_facts: no
  tasks:
    - assert:
        that:
          - vmanage_host is defined and vmanage_host
          - vmanage_user is defined and vmanage_host
          - vmanage_password is defined and vmanage_host
        fail_msg: "vmanage_host, vmanage_user, and vmanage_password must be defined"

    - name: Reading policy from {{ file }}
      set_fact:
        vmanage_policy: "{{ lookup('file',file) | from_json }}"

    - name: Import policy lists to {{ vmanage_host }}
      tags:
        - policy_lists
      vmanage_policy_list:
        user: "{{ vmanage_user }}"
        host: "{{ vmanage_host }}"
        password: "{{ vmanage_password }}"
        type: "{{ item.key }}"
        state: present
        aggregate: "{{ item.value }}"
      loop: "{{ lookup('dict', vmanage_policy.policy_lists) }}"
      when: item.value
      register: policy_list_facts

    - name: Import policy definitions to {{ vmanage_host }}
      tags:
        - policy_definitions
      vmanage_policy_definition:
        user: "{{ vmanage_user }}"
        host: "{{ vmanage_host }}"
        password: "{{ vmanage_password }}"
        type: "{{ item.key }}"
        state: present
        aggregate: "{{ item.value }}"
      loop: "{{ lookup('dict', vmanage_policy.policy_definitions) }}"
      when: item.value
      register: policy_list_facts

    - name: Import central policies to {{ vmanage_host }}
      tags:
        - central_policy
      vmanage_central_policy:
        user: "{{ vmanage_user }}"
        host: "{{ vmanage_host }}"
        password: "{{ vmanage_password }}"
        state: present
        aggregate: "{{ vmanage_policy.central_policies }}"
